In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("smsspamcollection.tsv",sep="\t")

In [4]:
df

label                                            message  length  punct
0      ham  Go until jurong point, crazy.. Available only ...     111      9
1      ham                      Ok lar... Joking wif u oni...      29      6
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3      ham  U dun say so early hor... U c already then say...      49      6
4      ham  Nah I don't think he goes to usf, he lives aro...      61      2
...    ...                                                ...     ...    ...
5567  spam  This is the 2nd time we have tried 2 contact u...     160      8
5568   ham               Will ü b going to esplanade fr home?      36      1
5569   ham  Pity, * was in mood for that. So...any other s...      57      7
5570   ham  The guy did some bitching but I acted like i'd...     125      1
5571   ham                         Rofl. Its true to its name      26      1

[5572 rows x 4 columns]

In [5]:
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [6]:
df.tail()

label                                            message  length  punct
5567  spam  This is the 2nd time we have tried 2 contact u...     160      8
5568   ham               Will ü b going to esplanade fr home?      36      1
5569   ham  Pity, * was in mood for that. So...any other s...      57      7
5570   ham  The guy did some bitching but I acted like i'd...     125      1
5571   ham                         Rofl. Its true to its name      26      1

In [7]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [8]:
df.shape[1]

4

In [9]:
df["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
df["length"].describe()

count    5572.000000
mean       80.489950
std        59.942907
min         2.000000
25%        36.000000
50%        62.000000
75%       122.000000
max       910.000000
Name: length, dtype: float64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   message  5572 non-null   object
 2   length   5572 non-null   int64 
 3   punct    5572 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 174.3+ KB


In [12]:
X=df[["length","punct"]]
y=df["label"]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.33, random_state=42)
print("Training Data Shape: ",X_train.shape)
print("Testing Data Shape: ",X_test.shape)


Training Data Shape:  (3733, 2)
Testing Data Shape:  (1839, 2)


In [15]:
from sklearn.linear_model import LogisticRegression

lr_model=LogisticRegression()

lr_model.fit(X_train, y_train)

LogisticRegression()

In [16]:
from sklearn import metrics

predictions=lr_model.predict(X_test)

print(metrics.confusion_matrix(y_test, predictions))

[[1547   46]
 [ 241    5]]


In [17]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         ham       0.87      0.97      0.92      1593
        spam       0.10      0.02      0.03       246

    accuracy                           0.84      1839
   macro avg       0.48      0.50      0.47      1839
weighted avg       0.76      0.84      0.80      1839



In [18]:
print(metrics.accuracy_score(y_test,predictions))

0.843936922240348


In [37]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train, y_train)

MultinomialNB()

In [41]:
from sklearn import metrics

predictions=nb_model.predict(X_test)

print(metrics.confusion_matrix(y_test, predictions))

[[1583   10]
 [ 246    0]]


In [43]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         ham       0.87      0.99      0.93      1593
        spam       0.00      0.00      0.00       246

    accuracy                           0.86      1839
   macro avg       0.43      0.50      0.46      1839
weighted avg       0.75      0.86      0.80      1839



In [45]:
print(metrics.accuracy_score(y_test,predictions))

0.8607939097335509


In [67]:
from sklearn.svm import SVC
svc_model=SVC(gamma="auto")
svc_model.fit(X_train, y_train)

SVC(gamma='auto')

In [69]:
predictions=svc_model.predict(X_test)

print(metrics.confusion_matrix(y_test, predictions))

[[1515   78]
 [ 131  115]]


In [71]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         ham       0.92      0.95      0.94      1593
        spam       0.60      0.47      0.52       246

    accuracy                           0.89      1839
   macro avg       0.76      0.71      0.73      1839
weighted avg       0.88      0.89      0.88      1839



In [73]:
print(metrics.accuracy_score(y_test,predictions))

0.8863512778684067


In [51]:
from sklearn.svm import SVC
svc_model=SVC()
svc_model.fit(X_train, y_train)

SVC()

In [55]:
predictions=svc_model.predict(X_test)

print(metrics.confusion_matrix(y_test, predictions))

[[1555   38]
 [ 193   53]]


In [57]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         ham       0.89      0.98      0.93      1593
        spam       0.58      0.22      0.31       246

    accuracy                           0.87      1839
   macro avg       0.74      0.60      0.62      1839
weighted avg       0.85      0.87      0.85      1839



In [59]:
print(metrics.accuracy_score(y_test,predictions))

0.8743882544861338
